services:
  db:
    image: postgres:15-alpine
    container_name: imobiliaria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=imobiliaria_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: imobiliaria_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=imobiliaria_db
      - DB_USER=admin
      - DB_PASS=admin

volumes:
  postgres_data: