# Generated by Django 6.0.5 on 2026-05-20 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='imoveis.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('legenda', models.CharField(blank=True, max_length=100)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('valor_fechado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='imoveis.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='imoveis.imovel')),
            ],
        ),
    ]
