# Generated by Django 6.0.5 on 2026-05-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contratoaluguel',
            options={'verbose_name': 'Contrato de Aluguel', 'verbose_name_plural': 'Contratos de Aluguel'},
        ),
        migrations.AlterModelOptions(
            name='imagemimovel',
            options={'verbose_name': 'Imagem do Imóvel', 'verbose_name_plural': 'Imagens dos Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
    ]
