# Generated by Django 6.0.5 on 2026-06-10 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_cliente_options_alter_contratoaluguel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imovel',
            name='aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=20),
        ),
        migrations.AddField(
            model_name='imovel',
            name='submetido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_submetidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
